### ISSUE TITLE
Make Renderers more Rails-y

### ISSUE THREAD

**Issue by chrislo** [alphagov/manuals-publisher#995]
e.g. use a `Presenter` suffix on the class name, move to a `app/presenters` directory, etc.

**Comment by floehopper** [comment]
As per [this comment](https://github.com/alphagov/manuals-publisher/pull/1023#pullrequestreview-34811844), @chrislo & I have agreed that rather than removing the renderers, this issue should be about converting them into more standard Rails presenters. Based on this, I'm going to change the title of this issue and move it out of the [Simplify milestone](https://github.com/alphagov/manuals-publisher/milestone/1) into the [Standardize milestone](https://github.com/alphagov/manuals-publisher/milestone/7).

**Comment by chrislo** [comment]
With the above PRs merged, we have now removed all of the "renderer" classes and replaced them with two new presenters `ManualPresenter` and `SectionPresenter`.
